#!/bin/bash

sbatch ./run.py 0606_base_fixed_ratio_t_200_alg_baseline_random_user_nearest_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_200_alg_baseline_random_user_random_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_200_alg_levelling2_random_user_nearest_poorest_taxi_w_waiting_limit
sbatch ./run.py 0606_base_fixed_ratio_t_3200_alg_baseline_random_user_nearest_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_3200_alg_baseline_random_user_random_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_3200_alg_levelling2_random_user_nearest_poorest_taxi_w_waiting_limit
sbatch ./run.py 0606_base_fixed_ratio_t_32_alg_baseline_random_user_nearest_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_32_alg_baseline_random_user_random_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_32_alg_levelling2_random_user_nearest_poorest_taxi_w_waiting_limit
sbatch ./run.py 0606_base_fixed_ratio_t_800_alg_baseline_random_user_nearest_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_800_alg_baseline_random_user_random_taxi
sbatch ./run.py 0606_base_fixed_ratio_t_800_alg_levelling2_random_user_nearest_poorest_taxi_w_waiting_limit
